#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    status-page-url-path: /swagger-ui.html

server:
  port: 8763
#  tomcat:
#    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:com/demo/mapper/*Mapper.xml

pagehelper:
  helper-dialect: mysql

logging:
  level:
    com.demo.dao: debug
    org.mongodb.driver: off

spring:
  application:
    name: SpringBoot
    version : 0.5.0
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 19930913
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  http:
#    encoding:
#      charset: UTF-8
#      force: true
#      enabled: true
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML
#    encoding: UTF-8
#    cache: false
#  resources:
#    chain:
#      strategy:
#        content:
#          enabled: true
#          paths: /**
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java
#      exclude: static/**,public/**

ftp:
  host: pc-jing
  port: 21
  username: 761878367@qq.com
  password:

email:
  smtp: smtp.163.com
  username: j150714101@163.com
  password: jm19930913








