eureka:
  client:
    service-url:
      defaultZone: http://dev:123456@localhost:8761/eureka/
  instance:
    status-page-url-path: /swagger-ui.html

server:
  port: 9001

mybatis:
  mapper-locations: classpath:com/demo/mapper/*Mapper.xml

pagehelper:
  helper-dialect: mysql

spring:
  application:
    name: SpringBoot
    version : 0.5.0
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 19930913
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    maxActive: 20
    maxWait: 60000
    testWhileIdle: true
    validationQuery: SELECT 1 FROM DUAL
    filters: wall,stat
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/demo
      username:
  servlet:
    multipart:
      max-file-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.163.com
    username: j150714101@163.com
    password: jm19930913

ftp:
  host: pc-jing
  port: 21
  username: 761878367@qq.com
  password: jm19930913.
  controlEncoding: utf-8
  passiveMode: false
  bufferSize: 1048576
  connectTimeOut: 10000
  dataTimeOut: 60000
  keepAliveTimeOut: 0

logging:
  level:
    com.demo.dao: debug
    org.mongodb.driver: off
  pattern:
    dateformat: 'yy-MM-dd HH:mm:ss'







